# Generated by Django 4.1 on 2022-08-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="OfferDis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="OfferPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("op_title", models.CharField(blank=True, max_length=20)),
                ("points", models.ManyToManyField(to="offers.description")),
            ],
        ),
        migrations.CreateModel(
            name="OfferModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offerTitle", models.CharField(max_length=40)),
                ("orderitems", models.ManyToManyField(to="offers.offerdis")),
            ],
        ),
        migrations.CreateModel(
            name="OfferEx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ex_title", models.CharField(max_length=80)),
                ("ex_dis", models.ManyToManyField(to="offers.offerpoint")),
            ],
        ),
        migrations.AddField(
            model_name="offerdis",
            name="offerex",
            field=models.ManyToManyField(to="offers.offerex"),
        ),
    ]
