# Generated by Django 4.1 on 2022-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_recentproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recentproduct",
            name="product_no",
            field=models.IntegerField(),
        ),
    ]
