# Generated by Django 4.1 on 2022-08-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_imagebulk_remove_product_product_image_and_more"),
        ("analysis", "0003_alter_recentproduct_product_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recentproduct",
            name="product_no",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
    ]
