# Generated by Django 4.0.3 on 2022-06-09 05:33

import django.core.validators
from django.db import migrations, models
import ecom.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='flashsale/banner', validators=[ecom.validators.check_image, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'svg', 'jpeg'])])),
                ('title', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_category', models.CharField(choices=[('mobile', 'mobile'), ('tv', 'tv'), ('tablet', 'tablet'), ('laptop', 'laptop')], default='mobile', max_length=120)),
                ('product_image', models.ImageField(upload_to='media/flashsale', validators=[ecom.validators.check_image, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'svg', 'jpeg'])])),
                ('product_description', models.TextField(max_length=500)),
                ('product_size', models.CharField(blank=True, choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extra large', 'extra large'), ('extra extra large', 'extra extra large')], max_length=20)),
                ('product_quantity', models.IntegerField()),
                ('product_available', models.BooleanField(default=True)),
                ('product_cost', models.BigIntegerField()),
                ('product_rating', models.FloatField(blank=True)),
                ('product_discount', models.IntegerField()),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
                ('product_color', models.ManyToManyField(to='products.colorf')),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ManyToManyField(to='flashsale.banner')),
                ('product', models.ManyToManyField(to='flashsale.flashsaleproduct')),
            ],
        ),
    ]
