# Generated by Django 4.0.3 on 2022-05-24 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_st', models.CharField(choices=[('Order Confirmed', 'order confirmed'), ('Order Processed', 'order Proccessed'), ('Order On The Way', 'order on the way'), ('Order Delivered', 'order delivered')], max_length=40)),
                ('comment', models.CharField(blank=True, max_length=120)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=12)),
                ('address_id', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uid', models.UUIDField(default=uuid.uuid1)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('order_status', models.CharField(choices=[('delivered', 'delivered'), ('processing', 'processing'), ('canceled', 'canceled')], default='processing', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_comnt', models.ManyToManyField(blank=True, to='order.orderstatus')),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
