# Generated by Django 4.0.3 on 2022-06-09 05:33

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecom.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('company_desc', models.CharField(max_length=120)),
                ('company_logo', models.ImageField(upload_to='media/brand', validators=[ecom.validators.check_image, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'svg', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='ColorF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='SubBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=120)),
                ('brand_image', models.ImageField(upload_to='media/subbrand', validators=[ecom.validators.check_image, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'svg', 'jpeg'])])),
                ('brandname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='SubDemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdemo', to='products.subbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.FloatField()),
                ('des', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_category', models.CharField(choices=[('mobile', 'mobile'), ('tv', 'tv'), ('tablet', 'tablet'), ('laptop', 'laptop')], default='mobile', max_length=120)),
                ('product_image', models.ImageField(upload_to='media/product', validators=[ecom.validators.check_image, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'svg', 'jpeg'])])),
                ('product_description', models.TextField(max_length=500)),
                ('product_size', models.CharField(blank=True, choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extra large', 'extra large'), ('extra extra large', 'extra extra large')], max_length=20)),
                ('product_quantity', models.IntegerField()),
                ('product_available', models.BooleanField(default=True)),
                ('product_cost', models.BigIntegerField()),
                ('product_rating', models.FloatField(blank=True)),
                ('product_discount', models.IntegerField()),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
                ('is_fav', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandsname', to='products.brand')),
                ('favourite', models.ManyToManyField(blank=True, related_name='post_favourite', to=settings.AUTH_USER_MODEL)),
                ('product_color', models.ManyToManyField(to='products.colorf')),
                ('reviews', models.ManyToManyField(blank=True, related_name='review', to='products.review')),
                ('sub_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='products.subbrand')),
            ],
        ),
    ]
